#!/bin/bash
# abort if one of the commands fail:
set -e 
set -o pipefail

# compile
( cd /home/ubuntu/elle-daniel/elle/processes/latte ; /home/ubuntu/elle-daniel/elle/processes/latte/compileMe ) > compile.log

# run latte
./runMe

# convert files
#elle2csv
#pvpython save-animation-from-csv.py
